### ISSUE TITLE
Please add this to packagist so that I can install via composer

### ISSUE THREAD

**Issue by simkimsia** [telegram-bot-kit/convo#19]
When I run 
```
composer require telegram-bot-kit/convo
```

In my laravel app, I get 
```
[InvalidArgumentException]
  Could not find package telegram-bot-kit/convo at any version for your minim
  um-stability (stable). Check the package spelling or your minimum-stability
```

Since there is no packagist for this yet, how do I install this into my laravel app?

**Comment by irazasyed** [comment]
You can clone the repo and add this to your composer.json file under autoload->psr-4. The API is likely to change as we're still working on decoupling and making major changes to the SDK itself. Hence, This wasn't released.
